name: Latest blog post workflow
on:
  schedule:
    # Runs every month
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          feed_list: "https://dev.to/feed/malibayram91,https://www.gautamkrishnar.com/feed/"
